services:
  postgres:
    image: postgres:13-alpine
    container_name: campus-postgres
    environment:
      POSTGRES_DB: campus_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: campus-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    container_name: campus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: campus-backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/campus_db
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - REDIS_URL=redis://redis:6379
      - BASE_URL=http://localhost:8000
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
      - redis
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: campus-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  elasticsearch_data:
  redis_data: