services:
  - type: web
    name: campus-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile.render
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campus-database
          property: connectionString
      - key: BASE_URL
        sync: false
      - key: ELASTICSEARCH_HOST
        value: ""
      - key: REDIS_URL
        value: ""
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /health

databases:
  - name: campus-database
    databaseName: campus_db
    user: campus_user
    plan: free
